first_name = input ('First Name: ')
last_name = input ('Last Name: ')
email = input ('Email Adress: ')
phone = input ('Phone Number: ')
job_title = input ('Job Ttle: ')
id = input ('ID Number: ')
eyes = input ('Eye Color: ')
hair = input ('Hair Color: ')
month = input ('Month started: ')
Training = input ('Training Completed Yes or No: ')

print('The ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print(job_title)
print(f'ID: {id}')
print(' ')
print(email.lower())
print(phone)
print('')
print(f'Eye Color: {eyes:15} Hair Color: {hair}')
print(f'Start Date: {month:14} Training: {Training}')
print('----------------------------------------')

